version: "3.3"
services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./server/
        target: /app
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    links:
      - server
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./client
        target: /app